spring:
  application:
    name: Discount-Application

  datasource:
    url: jdbc:postgresql://db:5432/discounts
    username: postgres
    password: 1475963
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
server:
  port: 3000
