version: '3.8'

services:
  backend:
    build: .
    container_name: discount-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_NAME: Discount-Application
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/discounts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

  db:
    image: postgres:16
    container_name: discount-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: discounts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
