spring:
  config:
    activate:
      on-profile: docker

  application:
    name: Discount-backend

  datasource:
    url: jdbc:postgresql://db:5432/discounts
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 465
    username: nurdaulet.beketov.2005@gmail.com
    password: dniulhublxbvpbdu
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

server:
  port: 3000

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key}
  accessTokenExpirationMs: 900000
  refreshTokenExpirationMs: 2592000000
