spring:
  application:
    name: Discount-Application

  datasource:
    url: jdbc:postgresql://localhost:5432/discounts
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 3000
