name: Test SSH Connection

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and run whoami
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "✅ SSH connection successful"
            whoami
            uptime
            hostname
